# Generated by Django 5.0.6 on 2024-06-20 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(blank=True, max_length=1, null=True)),
                ('location', models.CharField(max_length=100)),
                ('interests', models.ManyToManyField(blank=True, to='Account.interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInterests',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Account.profile')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.interest')),
            ],
        ),
    ]
